baseURL = 'https://dipro.fyi/'
languageCode = 'en-us'
title = 'Dipro Bhowmik'
theme = 'PaperMod'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Work'
    pageRef = '/posts'
    weight = 25
  [[menus.main]]
    name = 'Garden'
    pageRef = '/garden'
    weight = 30